Neos:
  Neos:
    fusion:
      autoInclude:
        'DL.HoneypotFormField': true

  Form:
    presets:
      'default':
        formElementTypes:
          'DL.HoneypotFormField:HoneypotField':
            superTypes:
              'Neos.Form:FormElement': true
              'Neos.Form:TextMixin': true
        finisherPresets:
          'DL.HoneypotFormField:SpamDetectionFinisher':
            implementationClassName: DL\HoneypotFormField\Finishers\SpamDetectionFinisher
            options: {  }

DL:
  HoneypotFormField:

    # If set to true, all finishers that are configured after the SpamDetectionFinisher are skipped.
    cancelSubsequentFinishersOnSpamDetection: false

    # Log the form data to the system log when classified as spam.
    logSpamFormData: false
